jdk:
  - openjdk8
install:
   - echo "Running a custom install command"
   - ./gradlew clean build generatePomFileForMavenPublication
   - echo "Done with clean, now customizing the pom.xml"   
   - sh scripts/process_pom.sh
   - echo "Publish to local maven"
   - ./gradlew publishMavenPublicationToMavenLocal
