language: java
matrix:
  include:
  - os: linux
    jdk: oraclejdk8
    sudo: false
  - os: osx
    osx_image: xcode7.3
script:
- mvn initialize
- mvn compile
after_success:
- chmod a+x sciview_deploy.sh
- bash sciview_deploy.sh
env:
  global:
  - secure: H/8SJwsrBdfm0vPx5pSKvVja8eCt2XdqTFau+a5zfQGfDIow72DUzHRlXwK7uFzHyjEDcR8o/pY9nhUnM0S+ScExIT4tyoE7vlCBtfA2bHhVLTXcSamHZkPN51cST1GZZsdR0dNXNKfFV8w2NQ2NudDfiIUog9chGH5ddSp0SBYpDDjY8IoLauggnQ+MQ1COVhaFBkzF3c4eeV1X2HrFtSLWEmfXR4SMGY7K3rD1vkPjRhC98e+7gEfe+6dnWxU6DDT+l8UhAPZrz0RwZduaxk7SyF7tf5bOmz1BL1ccDuJByb5yo4g0UbvvF9MfzOoBMqwx+8fol3UqlJbOIf/CY7IPh57UseH7hUjedYGTkw3ND42rKHXeP78uS9OSUFGMk6+9y7radFfBolgB/0eEIl1mvXceBG7TkjsNjxL8o0OZ9cLjuk+fyOP+P8GLGXWjblh9nJgk96VY8agO1nq0eQftb4gzFozwrX+ho+HfD0zY3JpjnCbatwSIqfsIm+aXlhzo53pVxtxCDCjrTnH8JTBr5zvs28ewiouocJx+x9OcR9dKVfS7VOYDmRh605oNOOWUrVLrFR9Ri4LIE5RL/Wn8jg4sNb2RKqTmvafJ3ERy5e1B2f1YF/vlnZNiEE57g+gdNWeJ3KwfKCG6siUMPZ+4wT1GQrgH27eE+zT0bGE=
  - secure: QJxBgiF4Ie971eIsOf41octitMb0HTSUzTq3mZp+6ZsHA6PDeiaTn1T5cPSaSfuk1p7C4tvuVzNz6sMAKxPDQGjO15hJh4tLWwe8cBt2or21EO7HJwuJX9vqWngwtjKlH8yHsDktvqxMGjqgPVGyVZaEpRIfAWhKl6s4ksrRcQMcxmnb6xsu7Us8GEvUf5eIc4577mXFYgRoO4GoXhAdD9edHMEjaPz6hDpf0rMYlrh5hl9ycpm6kZar+4UI/gRzvWCW/DZHkUHPyA574KjxTDsYgv61I1JVcxLUVYB+yULe7KpgvBYN0uIZRQhfjdMp8MOCMJ+i4CARG8PGZSBtSSRzHRdVH59hWcfoPLXC1YLW+jKEO3e9PU3iFqF6Qa7Kd6pRSFZDXyeVpExTMihLY7KtOBqiz4zq8G2ZbcBpGPaz122gTO16l5KIY0J8M0MdltoWK2qAC83yiEz3WUZV4V3F/a2ie7puIPHlYA/mZojZjlNBP5rBO+bBCXFUjHpT9AgzMYhiayYbmtVwLkEQkN0ExgaKl0ER73X7D2esHZAVR7sQyklWplnyfjt3w1uff2fWPS+VZLzLF3H+ovvSb03DWXgmFZOfpyuoSg2MoYgUAzdD2PVXt+Fwq1MapMqAzhIrqPQG/iHikQ4EaL/C4ASOHfuDmbnM/KEiwe5VF+c=
  - secure: JJ3ZHgtZMoX9+vUH4O8r64xtnY1qHlp+UBapsd1PnPWgn4SGUbmodLcMpFc+a1F2jXdeygHcZ/HkxYJWsOhmFqNmkvwR5Q9o+szsSSplS4mOUisdTlsJ+DruX/V6ftyLyD0YnC5LxU1DeSCmq2azHk2F+NpoK0TislCEKtAOPrzXlpPVgdjo2NSxTwUzAS5j5+KP1EVmQaXmlvqOZs/L4hS+cffpjXiB1qkEdxAUiMjJGvy9LcKxtBYpAX4HI8j9u5DRHqdI7GU548nzP9N4nF1FKYvAmqlVypryrHf1f+MLMDOBqKTA5AGKO7k8LArlMbh1pWk+rFHQDaXleCa37bHwurBwwOHuAYzTExmILdVris3bY/imzn1QfkKJnLghS73wfG5DvC/Z4Eu5Qq3qG8fFXQtirTkFgLyjVEmZCu7saPD1PRHhkSlSyR5mGYiuACxPXpDZBoZuDUB9k/6/Bkbrseh3Qg7kKxua3xHj2hE2CF/oH2Ofp9tKZE7rNI//f7NAo5nxjY7ti15ZYEzGflmhRCC5wDhdb6n2OHRM+qGcHjkpafztEwdGYzdfPhln5d++27xwak52F2Ph4spVGi5hxUD3AaCMOHCTcqOg6V1AAe1P90fpMKFVHn67z+77B2MHdH+bMGy+ht2J4S4aWWbaCfXjAgoytUuJDeJq+fM=
