name: sciview
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.8
#  - pyyaml
#  - numpy
#  - Pillow
#  - pyimagej
#  - opencv
#  - matplotlib
#  - openjdk
  - maven
  - git
  - openjdk >=8.0.192,<8.1.0a0
  - pip
  - pip:
      - pyinstaller
#    - tensorflow
#    - keras
