name: sciview
channels:
  - conda-forge
  - defaults
dependencies:
#  - pyyaml
#  - numpy
#  - Pillow
#  - pyimagej
#  - opencv
#  - matplotlib
#  - openjdk
  - maven
  - git
  - openjdk >=8.0.192,<8.1.0a0
#  - pip
#  - pip:
#    - tensorflow
#    - keras
